---
title: "species counts"
description: |
  A featured code project.
author:
  - name: Haley Grant
    url: {}
date: 03-14-2021
output:
  distill::distill_article:
    code_folding: true
    self_contained: false
---
The following graph shows counts over time for three fish species- Coho, Jack Coho, and Steelhead- at Willamette Falls between 2001 and 2010.[^1] I created this graph for a group assignment in ESM 244. With two other students in my group, we used Github to complete the assignment and gained experience solving merge conflicts.

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(prettydoc)
library(tidyverse)
library(dplyr)
library(here)
library(janitor)
library(lubridate)
library(tsibble)
library(feasts)
library(patchwork)
library(viridis)
library(rmdformats)
```

```{r}
seasonplot_ts <- read_csv(here("data","willamette_fish_passage.csv")) %>% 
       clean_names() %>% 
       select(coho, jack_coho, steelhead, date, temp_c) %>%
       mutate(date = mdy(date)) %>% 
       as_tsibble(key = NULL, index = date)
     
     seasonplot_week <- seasonplot_ts %>% 
       index_by(yr_wk = ~yearweek((.))) %>% 
       summarize(weekly_steelhead_counts = mean(steelhead), weekly_coho_counts = mean(coho), weekly_jack_coho_counts = mean(jack_coho)) 
     
     steelhead <- seasonplot_week %>% 
       gg_season(y = weekly_steelhead_counts,
                 pal = magma(10)) +
       theme_dark() +
       theme(axis.title = element_blank())
     
     coho <- seasonplot_week %>% 
       gg_season(y = weekly_coho_counts,
                 pal = magma(10)) +
       theme_dark() +
       theme(axis.title = element_blank())
     
     jack_coho <- seasonplot_week %>% 
       gg_season(y = weekly_jack_coho_counts,
                 pal = magma(10)) +
       theme_dark() +
       theme(axis.title = element_blank())
     
     steelhead + labs(subtitle = 'Steelhead') + 
       (jack_coho + labs(subtitle = 'Jack Coho') + 
          coho + labs(subtitle = 'Coho') +
          plot_layout(ncol = 1)) +
       plot_layout(guides = 'collect') +
       plot_annotation(title = 'Species Counts at Willamette Falls (2001-2010)') &
       theme(legend.position = 'bottom')
```

[^1]: Adult Passage Inventory Willamette Falls. Oregon Department of Fish & Wildlife, Columbia River DART (Data access in Real Time), 2000-2020. http://www.cbr.washington.edu/dart/query/adult_graph_text
